### PR TITLE
Centered content, added styling, added task card

### PR DESCRIPTION
**Pull request by rzerozy**
Changes:
- Centered content with Bootstrap
- Added background image to CSS file and linked to HTML
- Added task card to HTML
- Added icons to task card
- Added Google Font
- Changed heading colors and background

Things I learned:
- Elements need to be flex elements to use flex-properties like .justify-content-center
- You can center things without making them flex elements with .text-center
- Using breakpoints helps a ton with making the elements responsive
- Custom colors in Bootstrap require SASS so I had to use !important in CSS stylesheet to override Bootstrap theme

Still need to be done:
- Adjustments to heading backgrounds/colors

### CODE REVIEW

**Review by Ala4L — COMMENTED** [review]
Css looks great and task card is also on point!
I am just not sure why the main section Task List is doubled. When I open it in browser it looks like this.

**Review by Ala4L — APPROVED** [review]

**Review by bellecuddle — APPROVED** [review]

**Review by bellecuddle — APPROVED** [review]

**Review by bellecuddle — APPROVED** [review]

**Review by bellecuddle — APPROVED** [review]
Everything looks so good.

**Review by bellecuddle — APPROVED** [review]

**Comment by rzerozy** [comment]
> Css looks great and task card is also on point! I am just not sure why the main section Task List is doubled. When I open it in browser it looks like this. 

Weird! I wonder why it looks like that on your end. Here's what it looks like on mine:
image

image

**Review by bellecuddle — APPROVED** [review]

**Review by Churreesha — APPROVED** [review]
Looks good, I approve! 😊

**Pull request merged**
